### ISSUE TITLE
Structure change

### ISSUE THREAD

**Issue by SgnJp** [DanielJBlank/Testcases_CompilerConstruction16-17#1]
Let's change the structure from 
`exercise<number>/<initials>/[ok|error]/<initials>_<test_case_name>.java`
to 
`exercise<number>/[ok|error]/<initials>_<test_case_name>.java`

I guess it would be easier to use it directly, and the test case owner is defined by the initials at the begging of test name

**Comment by DanielJBlank** [comment]
Good idea. As we are only two for the moment, let's agree on this change and from now on use this new format. (I will reupload my testcases today/tomorrow). Then I will close this issue.

**Comment by DanielJBlank** [comment]
Reuploaded with the correct file structure.
